#6 get list of all user with points
JuniorsJava/gamification pull request #11
Opened 2016-12-11 19:29 UTC by Garazd

2016-12-12 08:06 UTC, adaleorion requested changes
@Garazd pls check.

2016-12-12 08:06 UTC, adaleorion commented on src/test/java/juja/microservices/gamification/achievement/AchievementRepositoryIntegrationTest.java
> +        list.get(1).getUserToId().equals("max");
Не ясно что проверяется, может лучше использовать assertEquals

2016-12-12 08:06 UTC, adaleorion commented on src/test/java/juja/microservices/gamification/achievement/AchievementRepositoryIntegrationTest.java
> +        list.get(0).getUserToId().equals("peter");
Не ясно что проверяется, может лучше использовать assertEquals

2016-12-12 08:06 UTC, adaleorion commented on src/main/java/juja/microservices/gamification/achivement/AchievementRepository.java
> +        }
У меня есть идея как избавиться от второго цикла при подсчете суммы point по users.

в ```UserPointsSum``` добавим метод ```addPoint(int addPoint)```  задачей которого будет добавлять ```addPoint``` к  ```pointCount```
в первом цикле в map мы будем добавлять сразу объекты ```UserPointsSum```, а если для user уже есть ```UserPointsSum``` то вызываем у него ```addPoint``` для накопления суммы.

В итоге после первого цикла у нас уже будет map с  ```UserPointsSum``` в которых будет сумма всех point для user.

2016-12-12 10:07 UTC, OlgaKulikova commented on src/test/java/juja/microservices/gamification/achievement/UserPointsSumTest.java
> +    public void shouldCreateAuthFromColonSeparated() {
Мне не понятно название теста. По сути вижу, что ты проверяешь конструктор и геттеры класса, мне кажется это избыточно.

2016-12-13 17:21 UTC, adaleorion approved these changes

2016-12-13 17:25 UTC, merged