Change feature of Keepers
JuniorsJava/gamification pull request #111
Opened 2017-07-11 07:47 UTC by VadimDyachenko

connect #99

2017-07-13 21:05 UTC, OlgaKulikova requested changes

2017-07-13 21:05 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/entity/KeeperDTO.java
> +    private List<String> direction;
please use plural for the name of list - directions.

2017-07-13 21:05 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/service/AchievementService.java
> +    private void addScheduledThanksKeeper() {
why this method private? where is it called from?

2017-07-13 21:05 UTC, OlgaKulikova commented on src/main/java/juja/microservices/gamification/service/AchievementService.java
> +    private void addScheduledThanksKeeper() {
Do you mean that scheduler can call it if it's private?

2017-07-13 21:05 UTC, OlgaKulikova commented on src/main/resources/application.properties
>  endpoint.keepers=/keepers
please consider that all services will have api version

2017-07-13 21:05 UTC, OlgaKulikova commented on src/main/resources/application.properties
> +cron.expression=* 0 0 * * SUN
please add a comment next to cron - how often it works

2017-07-13 21:05 UTC, OlgaKulikova commented
@VadimDyachenko please do update of upstream.

2017-07-14 04:51 UTC, VadimDyachenko commented on src/main/java/juja/microservices/gamification/entity/KeeperDTO.java
> +    private List<String> direction;
done

2017-07-14 04:52 UTC, VadimDyachenko commented on src/main/java/juja/microservices/gamification/service/AchievementService.java
> +    private void addScheduledThanksKeeper() {
I check it. This is work well

2017-07-14 04:53 UTC, VadimDyachenko commented on src/main/resources/application.properties
>  endpoint.keepers=/keepers
done

2017-07-14 05:03 UTC, VadimDyachenko commented on src/main/resources/application.properties
> +cron.expression=* 0 0 * * SUN
done

2017-07-14 05:26 UTC, VadimDyachenko commented
@OlgaKulikova Done!

2017-07-14 05:35 UTC, OlgaKulikova commented on src/main/resources/application.properties
> +#Schedueled task will run every Sunday at 00-00
Comments always should be written above code they describe. Put it up to one string.

2017-07-14 05:57 UTC, OlgaKulikova approved these changes

2017-07-14 05:57 UTC, merged