#93 Implement PointType Welcome
JuniorsJava/gamification pull request #94
Opened 2017-05-08 09:11 UTC by starikivan

connect to #93

2017-05-09 13:17 UTC, adaleorion requested changes
Привет, подскажи пожалуйста как мы решили с тестами, какие делаем обязательно, какие в виде новой таски, 

у тебя pr есть unit и acceptance, но нет integration ?

2017-05-09 16:29 UTC, OlgaKulikova requested changes
I agree, it should be integration test as well for new endpoint.
Everything else is good.

2017-05-10 11:01 UTC, starikivan commented
Integration tests for Welcome achievement were added.

2017-05-10 11:13 UTC, OlgaKulikova approved these changes

2017-05-10 19:44 UTC, adaleorion approved these changes

2017-05-10 19:44 UTC, merged